name: Build

defaults:
  run:
    shell: bash

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository and the juce submodule recursively
    - uses: actions/checkout@v2
      with:
        submodules: recursive

      # perform the build
    - uses: Barabas5532/juce-linux-build-action@v2

      # save the artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: linux-artifacts
        path: |
          build/*_artefacts
          !build/*_artefacts/JuceLibraryCode

  build-windows:
    runs-on: windows-latest
    steps:
      # Checkout the repository and the juce submodule recursively
    - uses: actions/checkout@v2
      with:
        submodules: recursive

      # perform the build
    - uses: Barabas5532/juce-windows-build-action@v2

      # save the artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: windows-artifacts
        path: |
          build/*_artefacts
          !build/*_artefacts/JuceLibraryCode
