name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository and the juce submodule recursively
    - uses: actions/checkout@v2
      with:
        submodules: recursive

      # perform the build
    - uses: Barabas5532/juce-linux-build-action@v2
    
    - run: |
      STANDALONE_PATH=`find build -wholename "*_artefacts/Standalone"
      VST3_PATH=`find build -wholename "*_artefacts/VST3"

      # save the artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: linux-standalone
        path: ${{ env.STANDALONE_PATH }}/*

    - uses: actions/upload-artifact@v2
      with:
        name: linux-vst3
        path: ${{ env.VST3_PATH }}/*
