name: Build

defaults:
  run:
    shell: bash

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository and the juce submodule recursively
    - uses: actions/checkout@v2
      with:
        submodules: recursive

      # perform the build
    - uses: Barabas5532/juce-linux-build-action@v2

      # save the artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: linux-artifacts
        path: |
          build/*_artefacts
          !build/*_artefacts/JuceLibraryCode

  build-windows:
    runs-on: windows-latest
    steps:
      # Checkout the repository and the juce submodule recursively
    - uses: actions/checkout@v2
      with:
        submodules: recursive

      # perform the build
    - uses: Barabas5532/juce-windows-build-action@v2

      # save the artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: windows-artifacts
        path: |
          build/*_artefacts
          !build/*_artefacts/JuceLibraryCode

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v2
      with:
        path: ~/artifacts

    - name: Display structure of downloaded files
      run: ls -R ~/artifacts

    # TODO rearrange files in artifacts so they make more sense for users
    #      Each format could be its own upload, and we should get rid of extra
    #      files.
    #
    #      Need to reset the executable bit on linux files, or tar them before
    #      artifact upload. (artifact upload does not preserve permissions)

    # Create the release, including the artifacts in it
    - uses: softprops/action-gh-release@v1
      with:
        files: ~/artifacts/*
    if: startsWith(github.ref, 'refs/tags/v')
