name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository and the juce submodule recursively
    - uses: actions/checkout@v2
      with:
        submodules: recursive

      # perform the build
    - uses: Barabas5532/juce-linux-build-action@v2

      # save the artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: linux-standalone
        path: build/*_artefacts/Standalone/*

    - uses: actions/upload-artifact@v2
      with:
        name: linux-vst3
        path: build/*_artefacts/VST3/*
